apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
        - name: chat-app
          image: alexanderrodnin/python-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials-secret
                  key: DB_PASSWORD
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials-secret
                  key: DB_USERNAME
            - name: DATABASE_NAME
              value: "postgres"
            - name: DATABASE_HOST
              value: "aurora-cluster-demo.cluster-cn6cgkw0sigm.us-east-1.rds.amazonaws.com"