name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/chat-demo-backend:latest

      - name: Set image public using GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          # Get the package ID for the Docker image
          PACKAGE_ID=$(gh api graphql -f query='
            query {
              organization(login: "${{ github.repository_owner }}") {
                packages(first: 100, names: ["chat-demo-backend"]) {
                  nodes {
                    id
                  }
                }
              }
            }
          ' --jq '.data.organization.packages.nodes[0].id')
          
          # Make the Docker image public
          gh api graphql -f query='
            mutation($packageId: ID!) {
              updatePackageVisibility(input: {packageId: $packageId, visibility: PUBLIC}) {
                package {
                  id
                }
              }
            }
          ' -F packageId=$PACKAGE_ID
