name: Retrieve Kubernetes Services

on:
  push:
    branches:
      - main

jobs:
  retrieve-services:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: arn:aws:iam::272405777365:role/github3
          aws-region: us-east-1
        run: |
          aws eks update-kubeconfig --region us-east-1 --name demo
          kubectl config current-context
          kubectl get svc
