name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Setup kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name demo

      - name: Get SVC
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: EKSTestingimage
          IMAGE_TAG: latest
        run: |
          kubectl get svc