name: Retrieve Kubernetes Services

on:
  push:
    branches:
      - main

jobs:
  retrieve-services:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: arn:aws:iam::272405777365:role/github3
          aws-region: us-east-1

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Setup kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name demo
          cat ~/.kube/config

      - name: Verify Kubernetes Context
        run: |
          kubectl config get-contexts
          kubectl config current-context

      - name: Get Kubernetes Services
        run: |
          kubectl get svc